version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - '1433:1433'
    volumes:
      - ./sql1data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password_11
      - MSSQL_PID=Express
